### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Uitalo** [upday7/TomatoClock#4]
I have:
Traceback (most recent call last):
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\TomatoClock\TomatoClock.py", line 124, in on_btn_start_clicked
    mw.overview._linkHandler("study")
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\TomatoClock\lib\component.py", line 132, in _linkHandler
    super(anki_overview, self)._linkHandler(url)
  File "aqt\overview.py", line 37, in _linkHandler
  File "anki\hooks.py", line 55, in repl
  File "aqt\main.py", line 388, in moveToState
    
  File "aqt\main.py", line 416, in _reviewState
    
  File "aqt\reviewer.py", line 54, in show
  File "aqt\reviewer.py", line 103, in nextCard
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\TomatoClock\lib\component.py", line 355, in _initWeb
    super(anki_reviewer, self)._initWeb()
  File "anki\hooks.py", line 55, in repl
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\jsbooster\review_hack.py", line 30, in customInitWeb
    self._showQuestion()
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\TomatoClock\lib\component.py", line 221, in _showQuestion
    self.db.question_card()
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\TomatoClock\lib\db.py", line 164, in question_card
    """, self.session_id, self.now, self.card.id, self.card.nid
  File "C:\Users\cassi\AppData\Roaming\Anki2\addons\TomatoClock\lib\db.py", line 139, in execute
    cur = super(TomatoDB, self).execute(sql, *a, **ka)
  File "anki\db.py", line 43, in execute
sqlite3.IntegrityError: tomato_session_item.session_id may not be NULL

**Comment by upday7** [comment]
fixed in version 0.2.35
