### ISSUE TITLE
Got an error 

### ISSUE THREAD

**Issue by Junyu25** [upday7/TomatoClock#5]
Got an error when passing the card.

Traceback (most recent call last):
  File "aqt\webview.py", line 157, in _loadFinished
  File "aqt\reviewer.py", line 182, in <lambda>
  File "C:\Users\***\AppData\Roaming\Anki2\addons\TomatoClock\lib\component.py", line 221, in _showQuestion
    self.db.question_card()
  File "C:\Users\***\AppData\Roaming\Anki2\addons\TomatoClock\lib\db.py", line 164, in question_card
    """, self.session_id, self.now, self.card.id, self.card.nid
  File "C:\Users\***\AppData\Roaming\Anki2\addons\TomatoClock\lib\db.py", line 139, in execute
    cur = super(TomatoDB, self).execute(sql, *a, **ka)
  File "anki\db.py", line 43, in execute
sqlite3.IntegrityError: NOT NULL constraint failed: tomato_session_item.session_id

**Comment by upday7** [comment]
fixed in version 0.2.35
