### ISSUE TITLE
Can someone please help out with an error?

### ISSUE THREAD

**Issue by ankiuser1995** [upday7/TomatoClock#6]
I don't know how to code at all, but this add-on was integral to my studying.  If someone could help me figure out how to fix this bug, it would be very very much appreciated. 

Traceback (most recent call last):
  File "aqt\main.py", line 165, in onOpenProfile
  File "aqt\main.py", line 244, in loadProfile
  File "anki\hooks.py", line 26, in runHook
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\tomatoClock.py", line 27, in start
    rr = TomatoClock.OneClockAddon()
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\TomatoClock.py", line 62, in __init__
    self.replace_mw_deckbrowser()
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\TomatoClock.py", line 72, in replace_mw_deckbrowser
    mw.deckBrowser.refresh()
  File "aqt\deckbrowser.py", line 30, in refresh
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\lib\component.py", line 97, in _renderPage
    tomato_summary=self.reports(),
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\lib\component.py", line 35, in reports
    if UserConfig.SHOW_OVERALL_STATISTICS else ""
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\lib\config.py", line 64, in __getattr__
    config_obj = load_config()
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\lib\config.py", line 63, in <lambda>
    load_config = lambda: cls.get_config(cls.metas[cls.__name__].__store_location__)
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\lib\config.py", line 125, in get_config
    disk_config_obj = _get_json_dict(cls.media_json_file)
  File "C:\Users\shaf1\AppData\Roaming\Anki2\addons\TomatoClock\lib\config.py", line 107, in _get_json_dict
    return json.load(ff)
  File "json\__init__.py", line 291, in load
  File "json\__init__.py", line 339, in loads
  File "json\decoder.py", line 364, in decode
  File "json\decoder.py", line 382, in raw_decode
ValueError: No JSON object could be decoded

**Comment by upday7** [comment]
this is not a vital error .
